---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  encryptedData:
    app: {{ .Values.app.sealedSecret.app }}
    jwt: {{ .Values.app.sealedSecret.jwt }}
  template:
    type: Opaque
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}