name: Test front container builds

on:
  push:
    branches-ignore: [ "main" ]
    paths:
      - 'images/front/*'
      - versions.txt

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # https://github.com/docker/setup-qemu-action
      - 
        name: Set up Docker
        uses: docker/setup-buildx-action@v3  # https://github.com/docker/setup-buildx-action
      - 
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.4.1
      - 
        name: Import versions.txt
        id: versions
        run: |
          for file in versions.txt images/front/versions.txt
          do
            [[ ! -f $file ]] && continue
            echo "-- Read $file"
            while IFS== read k v
            do
              [[ $k =~ \s*# ]] && continue
              echo "${k}=${v}"
              echo "${k}=${v}" >> $GITHUB_OUTPUT
              echo "${k}_SHORT=${v/@sha256*}"
              echo "${k}_SHORT=${v/@sha256*}" >> $GITHUB_OUTPUT
            done < "$file"
          done
      - 
        name: Build app
        uses: docker/build-push-action@v5  # https://github.com/docker/build-push-action
        with:
          push: false
          context: images/front
          platforms: linux/amd64
          build-args: |
            AENERIA_VERSION=${{ steps.versions.outputs.AENERIA_VERSION }}
            NGINX_VERSION=${{ steps.versions.outputs.NGINX_DIGEST_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
