name: Test front container builds

on:
  push:
    branches-ignore: [ "main" ]
    paths:
      - 'images/front/*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # https://github.com/docker/setup-qemu-action
      - 
        name: Set up Docker
        uses: docker/setup-buildx-action@v3  # https://github.com/docker/setup-buildx-action
      - 
        name: Import versions.txt
        id: versions
        uses: ./.github/actions/dotenv-action
        with:
          path: versions.txt
          keys-case: upper
          log-variables: true
          mask-variables: false
      - 
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.4.1
      - 
        name: Build app
        uses: docker/build-push-action@v5  # https://github.com/docker/build-push-action
        with:
          push: false
          context: images/front
          platforms: linux/amd64
          build-args: |
            AENERIA_VERSION=${{ steps.versions.outputs.AENERIA_VERSION }}
            NGINX_VERSION=${{ steps.versions.outputs.NGINX_DIGEST_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
