name: Publish released containers

on:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # https://github.com/docker/setup-qemu-action
      - 
        name: Set up Docker
        uses: docker/setup-buildx-action@v3  # https://github.com/docker/setup-buildx-action
      - 
        name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3  # https://github.com/docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract Docker metadata for app
        id: metadata-app
        uses: docker/metadata-action@v5  # https://github.com/docker/metadata-action
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-app
      - 
        name: Extract Docker metadata for front
        id: metadata-front
        uses: docker/metadata-action@v5  # https://github.com/docker/metadata-action
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-front
      - 
        name: Import versions.txt
        id: versions
        uses: ./.github/actions/dotenv-action
        with:
          path: versions.txt
          keys-case: upper
          log-variables: true
          mask-variables: false
      - 
        name: Build and push app
        uses: docker/build-push-action@v5  # https://github.com/docker/build-push-action
        with:
          push: true
          context: images/app
          platforms: linux/amd64,linux/arm64
          build-args: |
            AENERIA_VERSION=${{ steps.versions.outputs.AENERIA_VERSION }}
            PHP_FPM_VERSION=${{ steps.versions.outputs.PHP_FPM_DIGEST_VERSION }}
          tags: |
            ${{ github.repository }}:${{ steps.versions.outputs.AENERIA_VERSION }}
            ${{ github.repository }}:${{ steps.versions.outputs.AENERIA_VERSION }}-${{ steps.versions.outputs.PHP_FPM_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    

